Repository amaansyed27/thrive, pull requests merged in 2025-08, with the labels that each got.

#12 Created a Folder with files called Docs
  docs/architecture.md
  docs/copilot-instructions.md
  docs/file-description.md
  docs/index.md
  docs/references.md
  docs/working.md
Labels: documentation, GSSoC25, Level 1

#11 Updated Readme.md
  README.md
Labels: documentation, enhancement, GSSoC25, Level 1

#15 docs: Add contributing guidelines, issue, and pull request templatesDocs/add templates
  .github/ISSUE_TEMPLATE/issue.md
  .github/pull_request_template.md
  CONTRIBUTING.md
  Desktop/thriveproject/.github/ISSUE_TEMPLATE/issue.md
  Desktop/thriveproject/.github/pull_request_template.md
  Desktop/thriveproject/CONTRIBUTING.md
  Desktop/thriveproject/thrive/.gitignore
  Desktop/thriveproject/thrive/App.tsx
  Desktop/thriveproject/thrive/CODE_OF_CONDUCT.md
  Desktop/thriveproject/thrive/LICENSE.md
  Desktop/thriveproject/thrive/README.md
  Desktop/thriveproject/thrive/components/CodeOutput.tsx
  Desktop/thriveproject/thrive/components/EditorView.tsx
  Desktop/thriveproject/thrive/components/Footer.tsx
  Desktop/thriveproject/thrive/components/Header.tsx
  Desktop/thriveproject/thrive/components/LandingPage.tsx
  Desktop/thriveproject/thrive/components/Loader.tsx
  Desktop/thriveproject/thrive/components/PromptInput.tsx
  Desktop/thriveproject/thrive/constants.ts
  Desktop/thriveproject/thrive/docs/architecture.md
  Desktop/thriveproject/thrive/docs/copilot-instructions.md
  Desktop/thriveproject/thrive/docs/file-description.md
  Desktop/thriveproject/thrive/docs/index.md
  Desktop/thriveproject/thrive/docs/references.md
  Desktop/thriveproject/thrive/docs/working.md
  Desktop/thriveproject/thrive/index.html
  Desktop/thriveproject/thrive/index.tsx
  Desktop/thriveproject/thrive/metadata.json
  Desktop/thriveproject/thrive/package-lock.json
  Desktop/thriveproject/thrive/package.json
  Desktop/thriveproject/thrive/services/geminiService.ts
  Desktop/thriveproject/thrive/tsconfig.json
  Desktop/thriveproject/thrive/types.ts
  Desktop/thriveproject/thrive/vite.config.ts
Labels: documentation, GSSoC25, Level 1

#14 feat: implement dark and light mode theming with Zustand
  .gitignore
  App.tsx
  components/Header.tsx
  components/LandingPage.tsx
  index.html
  package-lock.json
  package.json
  store/index.ts
Labels: enhancement, good first issue, GSSoC25, Level 2

#16 Issue #6 ujjwal singh 20
  components/Header.tsx
  components/LandingPage.tsx
  components/SettingModal.tsx
  services/geminiService.ts
Labels: enhancement, good first issue, GSSoC25, Level 2

#19 Integrated CI/CD
  .github/workflows/cicd.yml
Labels: GSSoC25, Level 1

#22 Update Header component and NPM run build error
  App.tsx
  components/Header.tsx
Labels: bug, enhancement, GSSoC25, Level 2

#24 Fixed the logo on home page and in chat mode.
  components/EditorView.tsx
  components/Header.tsx
  components/LandingPage.tsx
  public/images/thrive_logo.png
  public/images/thrive_symbol.png
Labels: bug, GSSoC25, Level 1

#28 Pr create automate message
  .github/workflows/issue-create-automate-message.yml
  .github/workflows/pr-create-automate-message.yml
Labels: GSSoC25, Level 1
